FROM ubuntu:18.04

RUN apt update -y 
RUN apt install -y git
RUN apt install -y build-essential
RUN apt install -y cmake 
RUN apt install -y ninja-build
RUN apt install -y openssl && apt install -y  libssl-dev
RUN useradd -m backchannel 
RUN mkdir -p /home/backchannel/git
RUN git -C /home/backchannel/git clone https://github.com/Balluff/mosquitto.git -b feature/cpack
RUN git -C /home/backchannel/git  clone https://github.com/Balluff/libjson-rpc-cpp.git -b feature/cmake
RUN git -C /home/backchannel/git clone https://github.com/curl/curl.git
RUN mkdir -p /home/backchannel/build/curl
RUN cd /home/backchannel/build/curl && cmake -G "Ninja"  -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=OFF /home/backchannel/git/curl
 



